package fr.dta.projetFinal.enums;

import java.util.ArrayList;
import java.util.List;

public enum EnumGenres
{
	GENRE_COMBAT("GENRE_COMBAT"),
	GENRE_PLATEFORME("GENRE_PLATEFORME"),
	GENRE_FPS("GENRE_FPS"),
	GENRE_SHOOTTHEMUP("GENRE_SHOOTTHEMUP"),
	GENRE_RAILSHOOTER("GENRE_RAILSHOOTER"),
	GENRE_TPS("GENRE_TPS"),
	GENRE_ADVENTURE("GENRE_ADVENTURE"),
	GENRE_SIMULATEUR("GENRE_SIMULATEUR"),
	GENRE_ACTION("GENRE_ACTION"),
	GENRE_INFILTRATION("GENRE_INFILTRATION"),
	GENRE_SURVIVALHORROR("GENRE_SURVIVALHORROR"),
	GENRE_ACTIONRPG("GENRE_ACTIONRPG"),
	GENRE_HACKNSLASH("GENRE_HACKNSLASH"),
	GENRE_ROGUELIKE("GENRE_ROGUELIKE"),
	GENRE_MMORPG("GENRE_MMORPG"),
	GENRE_TACTICALRPG("GENRE_TACTICALRPG"),
	GENRE_JRPG("GENRE_JRPG"),
	GENRE_PUZZLE("GENRE_PUZZLE"),
	GENRE_LABYRINTHE("GENRE_LABYRINTHE"),
	GENRE_GESTION("GENRE_GESTION"),
	GENRE_TURNBASEDSTRATEGY("GENRE_TURNBASEDSTRATEGY"),
	GENRE_REALTIMESTRATEGY("GENRE_REALTIMESTRATEGY"),
	GENRE_4X("GENRE_4X"),
	GENRE_WARGAME("GENRE_WARGAME"),
	GENRE_SPORT("GENRE_SPORT"),
	GENRE_RACING("GENRE_RACING"),
	GENRE_RHYTHM("GENRE_RHYTHM");

	private String genre;
	
	private EnumGenres(String s)
	{
		this.genre = s;
	}

	public String getGenre()
	{
		return this.genre.toString();
	}

	public void setGenre(String genre)
	{
		this.genre = genre;
	}

	public static List<String> getAllGenres()
	{
		List<String> list = new ArrayList<String>();
		for(EnumGenres genre: EnumGenres.values()) {
			list.add(genre.getGenre());
		}
		return list;
	}
}